.TH JAMBASE 5 "30 August 1993"
.SH NAME
.B Jambase
\- 
.BR jam (1)
boilerplate
.SH FILES
.B /usr/local/lib/jam/Jambase
.br
.B Jamfile
.SH DESCRIPTION
.PP
.B Jambase
contains a set of
.B jam
rule definitions that provide roughly
.BR make (1)-like
functionality.
.B Jam
reads
.BR Jambase ,
which in turn includes the
.B Jamfile
from the current directory.
.PP
There are a number of built-in
.B jam
targets, including
.IR all ,
.IR exe ,
.IR files ,
.IR install ,
.IR lib ,
and
.IR shell .
The target
.I all
depends on
.IR exe ,
.IR files ,
.IR install ,
.IR lib ,
and
.IR shell .
.PP
The rules defined and variables used for the 
.B Jamfile 
are as follows:
.SS Rules
.PP
.IP "Main image : sources ;"
.IP
Compiles
.I sources
and links them into
.IR image ,
and makes
.I exe
depend on
.IR image .
.IP "LinkLibraries image : libraries ;"
.IP
Makes 
.I image
depend on
.I libraries
and includes them during the linking.
.IP "Setuid image ;"
.IP
Sets the setuid bit on
.I image
after linking.
.IP "Undefines image : symbols ;"
.IP
Tries to convince the loader that symbols need to be "undefined" for
the linking to work.
.IP "Library library : sources ;"
.IP
Compiles
.I sources
and archives them into 
.IR library .
The intermediate objects are deleted.
Makes
.I lib 
depend on
.IR libraries .
.IP "Object object : source ;"
.IP
Compiles a single source file
.I source
into
.IR object .
This rule is used by
.B Main
and 
.BR Library .
Makes
.I object
depend on all header files included by
.IR source .
Such dependencies are "soft": missing headers are not an error.
.IP
For 
.IR source , 
the following suffixes are recognized:
.RS
.IP .c
C source file
.IP .C
C++ source file
.IP .l
.IR lex (1)
source file.
The resulting lex.yy.c is renamed to be the same base as the
.IR source .
.IP .y
.IR yacc (1)
source file.  
The resulting y.tab.c and y.tab.h are renamed to the same base as
.IR source .
.PP
All other suffixes are passed to the rule
.IP
UserObject object : source ;
.PP
to be defined in the user's
.B Jamfile
(or elsewhere).
.RE
.IP "Bulk directory : sources ;"
.IP
Copies
.I sources
into 
.I directory
and makes
.I files
depend on all the targets.
.IP "File target : source ;"
.IP
Copies 
.I source
into 
.I target
and makes
.I files
depend on
.IR target.
.IP "Shell image : source ;"
.IP
Copies 
.I source
into the executable 
.BR sh (1)
script
.I image
and makes
.I shell
depend on
.IR image .
.IP "InstallBin sources ; "
.IP
Copy
.I sources
into /usr/local/bin.
Makes
.I install
depend on all targets.
.IP "InstallLib sources ;"
.IP
Copy
.I sources
into /usr/local/lib.
Makes
.I install
depend on all targets.
.IP "InstallMan sources ;"
.IP
Copy
.I sources
into the appropriate subdirectory of /usr/local/man.
Makes
.I install
depend on all targets.
.IP "RmTemps targets : sources ;"
.IP
Marks
.I sources
as temporary with the
.B TEMPORARY 
rule, and deletes
.I sources
once
.I targets
are built.
Must be the last rule invoked on
.IR targets .
Used internally by
.BR Object .
.SS Variables
.PP
AR (default
.IR "ar ru" )
.IP
The archiver used for
.BR Library .
.PP 
BINDIR (default
.IR "/usr/local/bin" )
.IP
The install directory for 
.BR InstallBin .
.PP 
CC (default
.IR cc )
.IP
C compiler used for
.BR Object .
.PP 
CCFLAGS (no default)
.IP
Flags handed to the C compiler for
.BR Object .
.B OPTIM
is also handed to the C compiler.
.PP 
EXEMODE (default 
.IR 711 )
.IP
Permissions for executables linked with
.BR Main .
.PP 
FILEMODE (default
.IR 644 )
.IP
Permissions for files copied by
.B File 
or
.BR Bulk .
.PP
HDRPATTERN (default ^#[\\t ]*include[\\t ]*[<"](.*)[">].*$)
.IP
The
.BR regexp (3)
pattern for finding header file includes in source files.
The 
.B Object
rule sets the 
.B jam
special variable
.B HDRSCAN
to
.RB $( HDRPATTERN )
for all of its sources.  The
.B Object
target depends on all header files found.
.PP 
HDRS (no default)
.IP
Directories to be scanned for header files and handed to the C
compiler with -I.  The
.B Object
rule sets
.B HDRS
to $(HDRS)
for each of its sources.
.PP
LEX (default 
.IR lex  )
.IP
The 
.BR lex (1)
command and flags.
.PP 
LIBDIR (default 
.IR /usr/local/lib )
.IP
The target directory for 
.BR InstallLib .
.PP
LINK (default 
.IR cc )
.IP
The linker.
.PP
LINKFLAGS (default 
.IR $(CCFLAGS) )
.IP
Flags handed to the linker.
.PP
LINKLinkLibraries (no default)
.IP
Libraries to hand to the linker.
The target image does not depend on these libraries.
.PP
LOCATE_TARGET (no default)
.IP
The directory for object modules and other intermediate files generated by
.BR Object .
This works by setting the
.B jam
special variable
.B LOCATE 
to the value of
.RB $( LOCATE_TARGET )
for each of 
.BR Object 's 
targets.
.PP
MV (default 
.IR "mv -f" )
.IP
The file rename command and options.
.PP
OPTIM (default 
.IR -O )
.IP
More flags handed to the C compiler.
.PP
RANLIB (default 
.IR ranlib )
.IP
If set, the command string to be invoked on each library after archiving.
.PP
RM (default 
.IR "rm -f" )
.IP
The command and options to remove a file.
.PP
SEARCH_SOURCE (no default)
.IP
The directory to find sources listed with
.BR Main ,
.BR Library ,
.BR Object ,
.BR Bulk ,
.BR File ,
.BR Shell ,
.BR InstallBin ,
.BR InstallLib ,
and
.BR InstallMan
rules.
This works by setting the
.B jam
special variable
.B SEARCH 
to the value of 
.RB $( SEARCH_SOURCE )
for each of the rules' sources.
.PP
SHELLHEADER (default 
.IR "#!/bin/sh" )
.IP
A string inserted to the first line of every file created by the
.B Shell
rule.
.PP
SHELLMODE (default 
.IR 755 )
.IP
Permissions for files installed by
.BR Shell .
.PP
STDHDRS (default 
.IR /usr/include )
.IP
Directories where headers can be found without resorting to using the
-I flag to the C compiler.
.PP
UNDEFFLAG (default 
.IR "\-u _" )
.IP
The flag prefixed to each symbol for the
.B Undefines 
rule.
.PP
YACc (default 
.IR "yacc -d" )
.IP
The 
.BR yacc (1)
command and flags.
.PP
JAMFile (default
.IR Jamfile )
.IP
The user provided file listing the sources to be built.

.SH BUGS
.PP
Because libraries are passed unbound to the 
.B Link 
rule as
.RB $( NEEDLIBS ), 
they cannot be located with 
.RB $( LOCATE ), 
because 
.RB $( LOCATE )
only changes the bound file name.
.PP
There's no 
.BR yacc (1)
on VMS, so the guts of the rules are commented out.

.SH EXAMPLES
.PP
.de XB
Example:
.RS
.IP
.ft CW
..
.de XE
.RE
.ft R
..
.XB
Main myprog : main.c util.c ;
.XE
.XB
LinkLibraries myprog : libstring.a libtree.a ;
.XE
.XB
Setuid myprog ;
.XE
.XB
Undefines myprog : treeinit ;
.XE
.XB
Library libstring.a : strcmp.c strcpy.c strlen.c ;
.XE
.XB
Object strcmp.o : strcmp.c ;
.XE
.XB
Bulk /usr/local/man/man1 : jam.1 myprog.1 ;
.XE
.XB
File /usr/local/lib/help.txt : help.txt ;
.XE
