.TH JAMBASE 5 "30 August 1993"
.SH NAME
\fBJambase\fR \- \fBjam\fR(1) boilerplate
.SH FILES
\fB/usr/local/lib/jam/Jambase\fR
.br
\fBJamfile\fR
.SH DESCRIPTION
.PP
\fBJambase\fR contains a set of \fBjam\fR rule definitions that provide
roughly \fBmake\fR(1)-like functionality.  \fBJam\fR reads
\fBJambase\fR, which in turn includes the \fBJamfile\fR from the
current directory.  This manual describes the support in \fBJambase\fR for
writing a \fBJamfile\fR.
.PP
There are a number of built-in \fBjam\fR targets, including \fIall\fR,
\fIexe\fR, \fIfiles\fR, \fIinstall\fR, \fIlib\fR, and \fIshell\fR.  The
target \fIall\fR depends on \fIexe\fR, \fIfiles\fR, \fIinstall\fR,
\fIlib\fR, and \fIshell\fR.
.PP
The rules defined and variables used for the \fBJamfile\fR are as
follows:
.SS Rules
.PP
.IP "Main image : sources ;"
.IP
Compiles \fIsources\fR and links them into \fIimage\fR, and makes
\fIexe\fR depend on \fIimage\fR.
.IP "LinkLibraries image : libraries ;"
.IP
Makes \fIimage\fR depend on \fIlibraries\fR and includes them during
the linking.
.IP "Setuid image ;"
.IP
Sets the setuid bit on \fIimage\fR after linking.
.IP "Undefines image : symbols ;"
.IP
Tries to convince the loader that symbols need to be "undefined" for
the linking to work.
.IP "Library library : sources ;"
.IP
Compiles \fIsources\fR and archives them into \fIlibrary\fR.  The
intermediate objects are deleted.  Makes \fIlib\fR depend on
\fIlibraries\fR.
.IP "Object object : source ;"
.IP
Compiles a single source file \fIsource\fR into \fIobject\fR.  This
rule is used by \fBMain\fR and \fBLibrary\fR.  Makes \fIobject\fR
depend on all header files included by \fIsource\fR.  Such dependencies
are "soft": missing headers are not an error.
.IP
For \fIsource\fR, the following suffixes are recognized:
.RS
.IP .c
C source file
.IP .C
C++ source file
.IP .l
\fIlex\fR(1) source file.  The resulting lex.yy.c is renamed to be the
same base as the \fIsource\fR.
.IP .y
\fIyacc\fR(1) source file.  The resulting y.tab.c and y.tab.h are
renamed to the same base as \fIsource\fR.
.PP
All other suffixes are passed to the rule
.IP
UserObject object : source ;
.PP
to be defined in the user's \fBJamfile\fR (or elsewhere).
.RE
.IP "Bulk directory : sources ;"
.IP
Copies \fIsources\fR into \fIdirectory\fR and makes \fIfiles\fR depend
on all the targets.
.IP "File target : source ;"
.IP
Copies \fIsource\fR into \fItarget\fR and makes \fIfiles\fR depend on
.IR target.
.IP "Shell image : source ;"
.IP
Copies \fIsource\fR into the executable \fBsh\fR(1) script \fIimage\fR
and makes \fIshell\fR depend on \fIimage\fR.
.IP "InstallBin sources ; "
.IP
Copy \fIsources\fR into /usr/local/bin.  Makes \fIinstall\fR depend on
all targets.
.IP "InstallLib sources ;"
.IP
Copy \fIsources\fR into /usr/local/lib.  Makes \fIinstall\fR depend on
all targets.
.IP "InstallMan sources ;"
.IP
Copy \fIsources\fR into the appropriate subdirectory of
/usr/local/man.  Makes \fIinstall\fR depend on all targets.
.IP "RmTemps targets : sources ;"
.IP
Marks \fIsources\fR as temporary with the \fBTEMPORARY\fR rule, and
deletes \fIsources\fR once \fItargets\fR are built.  Must be the last
rule invoked on \fItargets\fR.  Used internally by \fBObject\fR.
.SS Variables
.PP
AR (default \fI"ar ru"\fR)
.IP
The archiver used for \fBLibrary\fR.
.PP
BINDIR (default \fI/usr/local/bin\fR)
.IP
The install directory for \fBInstallBin\fR.
.PP
CC (default \fIcc\fR)
.IP
C compiler used for \fBObject\fR.
.PP
CCFLAGS (no default)
.IP
Flags handed to the C compiler for \fBObject\fR.  \fBOPTIM\fR is also
handed to the C compiler.
.PP
EXEMODE (default \fI711\fR)
.IP
Permissions for executables linked with \fBMain\fR.
.PP
FILEMODE (default \fI644\fR)
.IP
Permissions for files copied by \fBFile\fR or \fBBulk\fR.
.PP
HDRPATTERN (default ^#[\\t ]*include[\\t ]*[<"](.*)[">].*$)
.IP
The \fBregexp\fR(3) pattern for finding header file includes in source
files.  The \fBObject\fR rule sets the \fBjam\fR special variable
\fBHDRSCAN\fR to $(\fBHDRPATTERN\fR) for all of its sources.  The
\fBObject\fR target depends on all header files found.
.PP
HDRS (no default)
.IP
Directories to be scanned for header files and handed to the C compiler
with -I.  The \fBObject\fR rule sets \fBHDRS\fR to $(HDRS) for each of
its sources.
.PP
LEX (default \fIlex\fR )
.IP
The \fBlex\fR(1) command and flags.
.PP
LIBDIR (default \fI/usr/local/lib\fR)
.IP
The target directory for \fBInstallLib\fR.
.PP
LINK (default \fIcc\fR)
.IP
The linker.
.PP
LINKFLAGS (default \fI$(CCFLAGS)\fR)
.IP
Flags handed to the linker.
.PP
LINKLIBS (no default)
.IP
Libraries to hand to the linker.  The target image does not depend on
these libraries.
.PP
LOCATE_TARGET (no default)
.IP
The directory for object modules and other intermediate files generated
by \fBObject\fR.  This works by setting the \fBjam\fR special variable
\fBLOCATE\fR to the value of $(\fBLOCATE_TARGET\fR) for each of
\fBObject\fR's targets.
.PP
MV (default \fImv -f\fR)
.IP
The file rename command and options.
.PP
OPTIM (default \fI-O\fR)
.IP
More flags handed to the C compiler.
.PP
RANLIB (default \fIranlib\fR)
.IP
If set, the command string to be invoked on each library after
archiving.
.PP
RM (default \fIrm -f\fR)
.IP
The command and options to remove a file.
.PP
SEARCH_SOURCE (no default)
.IP
The directory to find sources listed with \fBMain\fR, \fBLibrary\fR,
\fBObject\fR, \fBBulk\fR, \fBFile\fR, \fBShell\fR, \fBInstallBin\fR,
\fBInstallLib\fR, and \fBInstallMan\fR rules.  This works by setting
the \fBjam\fR special variable \fBSEARCH\fR to the value of
$(\fBSEARCH_SOURCE\fR) for each of the rules' sources.
.PP
SHELLHEADER (default \fI#!/bin/sh\fR)
.IP
A string inserted to the first line of every file created by the
\fBShell\fR rule.
.PP
SHELLMODE (default \fI755\fR)
.IP
Permissions for files installed by \fBShell\fR.
.PP
STDHDRS (default \fI/usr/include\fR)
.IP
Directories where headers can be found without resorting to using the
\fIflag\fR to the C compiler.
.PP
UNDEFFLAG (default \fI-u _\fR)
.IP
The flag prefixed to each symbol for the \fBUndefines\fR rule.
.PP
YACc (default \fIyacc -d\fR)
.IP
The \fByacc\fR(1) command and flags.
.PP
JAMFILE (default \fIJamfile\fR)
.IP
The user provided file listing the sources to be built.

.SH BUGS
.PP
Because libraries are passed unbound to the \fBLink\fR rule as
$(\fBNEEDLIBS\fR), they cannot be located with $(\fBLOCATE\fR), because
$(\fBLOCATE\fR) only changes the bound file name.
.PP
There's no \fByacc\fR(1) on VMS, so the guts of the rules are commented
out.

.SH EXAMPLES
.PP
.de XB
Example:
.RS
.IP
.ft CW
..
.de XE
.RE
.ft R
..
.XB
Main myprog : main.c util.c ;
.XE
.XB
LinkLibraries myprog : libstring.a libtree.a ;
.XE
.XB
Setuid myprog ;
.XE
.XB
Undefines myprog : treeinit ;
.XE
.XB
Library libstring.a : strcmp.c strcpy.c strlen.c ;
.XE
.XB
Object strcmp.o : strcmp.c ;
.XE
.XB
Bulk /usr/local/man/man1 : jam.1 myprog.1 ;
.XE
.XB
File /usr/local/lib/help.txt : help.txt ;
.XE
